# Configure radios
---
- name: Upload init script
  action: scp src={{role_path}}/files/poe dest=/etc/init.d/

- name: Enable poe
  raw: /etc/init.d/poe enable

- name: Start poe
  raw: /etc/init.d/poe start
